version: "3.8"

services:
  app:
    build: ./
    depends_on:
      - db
    networks:
      - backend
    env_file:
      - .env
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "${PG_EXTERNAL_PORT}:${PG_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    env_file:
      - .env

volumes:
  postgres-data:
    driver: local

networks:
  backend:
