version: "3.8"
services:
  app :
    build: ./
    env_file:
      - .env
  db:
    build: ./database/
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    env_file:
      - .env
