version: "3.8"
services:
  app:
    build: ./
    env_file:
      - .env
  db:
    restart: always
    build: ./database/
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
