version: "3.8"
services:
  app:
    build: ./
    env_file:
      - .env
  db:
    image: postgres:15.4
    restart: always
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
    driver: local
